services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - api-gateway/.env
    networks:
      - internal

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8081:8081" # dev purposes
    env_file:
      - auth-service/.env
    networks:
      - internal

networks:
  internal:
    external: true