services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - api-gateway/.env
    networks:
      - internal
    volumes:
      - maven-repo:/root/.m2

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    env_file:
      - auth-service/.env
    networks:
      - internal
    volumes:
      - maven-repo:/root/.m2

  item-service:
    container_name: item-service
    build:
      context: .
      dockerfile: item-service/Dockerfile
    env_file:
      - item-service/.env
    networks:
      - internal
    volumes:
      - maven-repo:/root/.m2

networks:
  internal:
    external: true

volumes:
  maven-repo: